BUGFIX: Language fallback handling for canonical and alternate language links
neos/neos-seo pull request #154
Opened 2021-01-25 16:24 UTC by Sebobo

The canonical link will now link to the original node if a dimension fallback is active.

The list of alternate language links will not contain nodes anymore if they don't exist in the target language.

2021-01-25 19:30 UTC, jonnitto approved these changes

2021-01-26 07:37 UTC, regniets commented
Thanks for fixing this issue!

This is nevertheless a breaking change which could impact many websites to the negative.
You mostly have reasonable fallbacks like en-us > en which do make sense and should have hreflang and canonical to themselves.
But there are cases (like on neos.io) that fall back from de > en. Now your hreflang is faulty because you show english content flagged german. 
I would not recommend merging this fix as it is. We could 
1. Provide only a gist to show how to handle it (and/or write documentation for this special case)
2. Provide a feature flag in order to activate it in case you need.

What we are trying to handle might actually be quite an edge case...
What do you think?

2021-01-26 07:38 UTC, regniets requested changes, later dismissed
Code is fine, but see my comment on use case.

2021-01-26 08:36 UTC, Sebobo commented
I disagree that it's an edge case. Actually most projects I'm involved with which use multiple languages use fallbacks to completely different languages. Most of the time everything falls back to English and the customers want to have a full page tree in all languages as they don't know when they are able to localise everything.

I also don't really see the negative SEO effect. Why should the UK version when it's not localised have its own canonical and language link?

If this is really required to be defined on a per preset basis we might need additional options in the presets or in the SEO settings.

2021-01-26 08:58 UTC, regniets commented
Got it - and good to know there are many websites that will benefit (so will neos.io)!

But we are introducing something that will have an effect on many websites that are using this package
(I would not want this to happen unnoticedly).

Flagging derivates is a main use case of hreflang. When i have a website for Austria (.at) that shares most of the content with the german version (.de) but has different products, i would want the austrian user to find austrian results (de-at). 
If i let most of the pages point to their de version, austrian people would end up most likely on my .de website.

2021-01-26 09:01 UTC, Sebobo commented
So you mean regarding the canonical and alternate language links the new behaviour should be behind a feature flag, which we might inverse with a major release?

2021-01-26 09:04 UTC, regniets commented on Resources/Private/Fusion/Metadata/AlternateLanguageLinks.fusion
> +                @if.existsInTargetDimensions={item.node.dimensions == item.node.context.targetDimensionValues}
Checked the hreflang specs. We need to remove hreflang here as nothing points to this version.
Actually "@if.hasNoForeignCanonical" needs to be adapted as it does have a foreign canonical
https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en

2021-01-26 09:07 UTC, bwaidelich commented
I'm not into SEO that much (I just know that duplicate content is bad) so I can't really vote on this change. But from my own experience I can tell that breaking changes in this package can be very harmful because they can be very subtle. When I updated a large project recently it introduced a different set of metatags leading to a downgrade on Google.
So in general I think, a feature flag might be a good idea.
And for the long run it might be a solution to have some more CLI tools to setup/verify SEO settings interactively

2021-01-26 09:21 UTC, Sebobo commented on Resources/Private/Fusion/Metadata/AlternateLanguageLinks.fusion
> +                @if.existsInTargetDimensions={item.node.dimensions == item.node.context.targetDimensionValues}
Don't fully understand what needs to be done from your description.

2021-01-26 09:21 UTC, regniets commented
@Sebobo - i think a feature flag might be the best solution.
@bwaidelich - i just happen to have some knowledge in hreflang, but from my experience a lot of people don't - so i consider it dangerous as well. I like the cli tool idea; just the featureset of neos/seo is pretty advanced already, maybe there won't be so many options to be set.

2021-01-26 09:27 UTC, regniets commented on Resources/Private/Fusion/Metadata/AlternateLanguageLinks.fusion
> +                @if.existsInTargetDimensions={item.node.dimensions == item.node.context.targetDimensionValues}
actually something like 
@if.hasNoForeignCanonical = ${String.isBlank(q(this.node).property('canonicalLink'))}
@if.nodeIsTranslated = ${this.node.dimensions == this.node.context.targetDimensionValues}

2021-01-26 10:14 UTC, Sebobo commented on Resources/Private/Fusion/Metadata/AlternateLanguageLinks.fusion
> +                @if.existsInTargetDimensions={item.node.dimensions == item.node.context.targetDimensionValues}
Ah ok, so an additional check for the canonical

2021-09-01 11:27 UTC, Sebobo commented
A customer of mine required the same fix today for a project with many languages and 2 dimensions. 
I applied it there including @regniets adjustments and will finish up this PR when they are happy with it.

2022-05-30 08:00 UTC, kdambekalns reviewed
> […] and will finish up this PR when they are happy with it.

Any news?

2022-10-14 16:20 UTC, regniets commented
indeed, got a customer project as well now that could need the fix :)

2022-10-27 14:59 UTC, mbiberger commented on Resources/Private/Fusion/Metadata/AlternateLanguageLinks.fusion
> +                @if.existsInTargetDimensions={item.node.dimensions == item.node.context.targetDimensionValues}
In our case, no hreflang is output when I only adjust content on a page that has a language fallback.
We have now added the following queries in Neos.Seo:AlternateLanguageLink:
`    @if.hasMetaRobotsNoIndexNotSet = ${q(this.node).property('metaRobotsNoindex') || q(this.node).is('[instanceof Neos.Seo:NoindexMixin]') ? false : true}
    @if.hasNoForeignCanonical = ${String.isBlank(q(this.node).property('canonicalLink'))}
`

2025-11-06 12:44 UTC, Sebobo commented
> > […] and will finish up this PR when they are happy with it.
> 
> Any news?

Yes, I updated the PR, as I just needed the patch again 😄

2026-01-12 12:04 UTC, Sebobo commented
This will need a separate implementation for Neos 9, as I just had the some of the problems yet again on neos.io.

2026-03-29 17:37 UTC, dlubitz commented
@Sebobo See #199 for Neos 9 implementation

2026-05-25 07:05 UTC, dlubitz approved these changes
We should merge this, but revert it fully on upmerge. As we aleady have 9.x implementatin in 4.x branch

2026-06-03 12:07 UTC, merged