TASK: Add google-site-verification meta tag
neos/neos-seo pull request #165
Opened 2022-02-03 08:55 UTC by Benjamin-K

When using the google search console to have a better overview about search results of your site, till now you had to add the required meta tag (or verification file or header) yourself for each project. 

This pull request adds a property to the seo tags so you can easily add your google-site-verification meta tag. Output will be 

```html
<meta name="google-site-verification" content="yourGoogleSiteVerificationProperty" />
```

2022-02-03 09:10 UTC, kdambekalns reviewed
Looks good… but… 😇

Having this as a node property seems wrong, as it's a site-wide thing. Maybe handle it in the settings instead?

2022-02-03 09:42 UTC, Benjamin-K commented
What's the problem with having it as a node property? I think this is much easier to maintain than the settings. Plus: Having it in the settings requires us to handle multi-site setups more carefully, which will not be the case with a node property.

2022-02-03 10:17 UTC, Sebobo commented
It only needs to be applied to the homepage right?
Then we could have it as a separate mixin and devs can set it as super type to their homepage NodeType.
And in Fusion we can add the condition that its only rendered if `node == site`.

Wdyt?

2022-02-03 10:30 UTC, kdambekalns commented
> What's the problem with having it as a node property? 

It can easily lead to confusion if added on more nodes than just the site node. What will Google think? What will users expect?

2022-02-03 10:33 UTC, kdambekalns commented
> It only needs to be applied to the homepage right? Then we could have it as a separate mixin and devs can set it as super type to their homepage NodeType.

That would be a nice addition!

I'd still love to be able to set it via settings. That way it can be populated from an env variable in different server environments.

> And in Fusion we can add the condition that its only rendered if `node == site`.

Awesome.

2022-02-03 11:06 UTC, Benjamin-K commented
Good catches. So i will create a new mixin for that and update the docs. The fusion does not have to be changed (except for the  `node == site` condition).

What would you expect when setting the property via settings? We should handle multi-site setups when having the property via settings, too.

How about:
```yaml
Neos:
  Seo:
    googleSiteVerification:
      'siteNodeIdentifier': 'googleSiteVerificationProperty'
```

2022-02-03 13:36 UTC, Benjamin-K commented
Another solution for the node property could be:

```yaml
'Neos.Seo:SeoMetaTagsMixin':
  properties:
    metaGoogleSiteVerification:
      ui:
        inspector:
          hidden: 'ClientEval: node.depth > 2'
```

2022-02-03 13:47 UTC, Sebobo commented
I personally don't want properties on nodes that I don't need. So I definitely prefer the mixin to control the feature individually.

2022-02-03 14:12 UTC, kdambekalns commented
> What would you expect when setting the property via settings?

It should be used as default value, I could then disable/hide the property and have it "settings-only". Or leave the property in place and it would override the setting.

> We should handle multi-site setups when having the property via settings, too.

Definitely, possibly for other settings as well. I like the way it's done here:

https://github.com/neos/neos-googleanalytics/blob/164bdc771862c44aa343138a155963c3aee5b83f/Configuration/Settings.yaml#L52-L62

2022-02-03 14:46 UTC, Benjamin-K commented
Ok, i updated my commit to have settings as fallback and a mixin that could be added to the nodeType of the site node. Also i updated the documentation. I did not yet implement the multi site setup via settings, but that should be ok for now i think.

2022-02-03 14:59 UTC, Benjamin-K commented
> Definitely, possibly for other settings as well. I like the way it's done here:
> 
> https://github.com/neos/neos-googleanalytics/blob/164bdc771862c44aa343138a155963c3aee5b83f/Configuration/Settings.yaml#L52-L62

I like that way, too. But that should be a separate PR i think. And the change should not be breaking if possible.

2022-02-03 15:30 UTC, Benjamin-K commented on Resources/Private/Fusion/Metadata/GoogleSiteVerification.fusion
> +    @context.googleSiteVerification = ${q(node).property('metaGoogleSiteVerification') || Configuration.setting('Neos.Seo.google.siteVerification')}
Updated the prototype to extend from `Neos.Fusion:Component`.

2022-02-04 08:04 UTC, Sebobo approved these changes
Looks good to me by reading.

2022-02-04 09:48 UTC, jonnitto requested changes

2022-02-04 09:48 UTC, jonnitto commented on Resources/Private/Fusion/Metadata/GoogleSiteVerification.fusion
> +            @if.hasGoogleSiteVerification={props.googleSiteVerification}
Remove this line

2022-02-04 09:48 UTC, jonnitto commented on Resources/Private/Fusion/Metadata/GoogleSiteVerification.fusion
> +    @if.isSite = ${node == site}
`@if.isSiteAndHasGoogleSiteVerification = ${node == site && this.googleSiteVerification}`

2022-02-04 09:56 UTC, Benjamin-K commented on Resources/Private/Fusion/Metadata/GoogleSiteVerification.fusion
> +    @if.isSite = ${node == site}
Used two `@if` statements here, but change is applied.

2022-02-04 15:20 UTC, jonnitto approved these changes

2022-02-04 15:20 UTC, merged