fix: regex is failing on a proper verification code
neos/neos-seo pull request #181
Opened 2023-11-16 15:40 UTC by hphoeksma

Fixes: #180

2023-11-24 23:34 UTC, jonnitto approved these changes
Fine by reading

2024-03-14 11:43 UTC, Benjamin-K commented
Google now also has an underscore sometimes. Maybe also dashes? So i think we should update the regex to match such verification codes to. Sth. like:

``` regularExpression: '/^[a-zA-Z0-9_-]+$/'```

2024-03-20 08:57 UTC, jonnitto requested changes

2024-03-20 08:57 UTC, jonnitto commented on Configuration/NodeTypes.Mixin.GoogleSiteVerification.yaml
> +          regularExpression: '/^[a-zA-Z0-9]+$/'
```suggestion
          regularExpression: '/^[a-zA-Z0-9_-]+$/'
```

2024-03-20 08:58 UTC, jonnitto approved these changes

2024-03-20 08:58 UTC, merged

2024-03-20 09:00 UTC, jonnitto commented
https://github.com/neos/neos-seo/releases/tag/3.3.5